version: "3.9"

services:
  backend:
    build: ./backend
    command: [ "/bin/sh", "/backend/docker/app.sh" ]
    expose:
      - 8000
    ports:
      - "8000:8000"

  client:
    build: ./client
    expose:
      - 3000
    ports:
      - "3000:3000"
    command: npm run dev -- --port 3000
    depends_on:
      - backend